# http://docs.travis-ci.com/user/languages/android/
language: android
jdk: oraclejdk8

#Sudo added because a license needs to be manually added
sudo: required
 
# Git permission acces for Travis and license to use ConstraintLayout
before_install:
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- chmod +x gradlew
 
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project and emulator version
    - android-26
    # Adding System Images for the emulators
    - sys-img-armeabi-v7a-android-26
  
script:
   - ./gradlew build connectedCheck
