# http://docs.travis-ci.com/user/languages/android/
language: android
jdk: oraclejdk8

#Sudo added because a license needs to be manually added
sudo: required
 
# Git permission acces for Travis and license to use ConstraintLayout
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > 
"$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
 
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-26
    
script:
   - ./gradlew build connectedCheck
