# http://docs.travis-ci.com/user/languages/android/
language: android
jdk: oraclejdk8
 
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-26
    
script:
   - ./gradlew build connectedCheck
